version: "3.9"

services:

  store-intelligence-api:

    build:
      context: ..

      dockerfile: infra/Dockerfile

    container_name: store-intelligence-api

    ports:
      - "8000:8000"

    volumes:
      - ../data:/app/data

    restart: always